/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.IOException;

import com.indvd00m.ascii.render.Render;
import com.indvd00m.ascii.render.api.ICanvas;
import com.indvd00m.ascii.render.api.IContextBuilder;
import com.indvd00m.ascii.render.elements.Ellipse;
//import com.indvd00m.ascii.render.elements.PseudoText;
import com.indvd00m.ascii.render.elements.Rectangle;

public class App {

    public String getGreeting() {
        return "Hello World!";
    }
    public static void main(String[] args) throws IOException {
        System.out.println(new App().getGreeting());

        /*  // Ascii Render Example
        Render render = new Render();
        IContextBuilder builder = render.newBuilder();
        builder.width(120).height(20);
       // builder.element(new PseudoText("DevOps"));
        builder.element(new PseudoText("Cansu"));
        ICanvas canvas = render.render(builder.build());
        String s = canvas.getText();
        System.out.println(s);
        */
        
        //Eclipe Beispiel 
		Render render = new Render();
		IContextBuilder builder = render.newBuilder();
		builder.width(20).height(10);
		builder.element(new Rectangle());
		builder.element(new Ellipse(9, 4, 14, 6));
		ICanvas canvas = render.render(builder.build());
		String s = canvas.getText();
		System.out.println(s);

   //private static Render extracted(Render render) {
     //   return render;
    //}
}

}